import type { Prisma } from "@prisma/client";

/**
 * DEMO COURSES — clearly-marked placeholder data used only to demonstrate the
 * Online Courses UI before real affiliate courses are inserted.
 *
 * IMPORTANT: none of this is real. Every course here has `demo: true` (the UI
 * shows a "Demo" badge and a disclaimer), NO affiliate URL (the CTA shows a
 * "link coming soon" state), and placeholder instructor/rating/price/review
 * values. Replace these with real Udemy/Impact courses from the admin panel,
 * or delete them once real courses exist. Titles/instructors are generic and
 * do not represent real Udemy listings.
 */

const IMG = (seed: string) =>
  `https://placehold.co/640x360/0a1f44/ffffff/png?text=${encodeURIComponent(seed)}`;

/**
 * TEST affiliate URL only — the owner's first Impact/Udemy tracking link, used
 * solely so the "View on Udemy" button is clickable while previewing the demo.
 *
 * This is NOT a shared/permanent link: it lives on these demo rows only. Every
 * REAL course gets its OWN unique Impact URL entered per-course in the admin
 * (Course.affiliateUrl). The frontend always resolves each course's own URL.
 */
const TEST_AFFILIATE_URL = "https://trk.udemy.com/aNDLqW";

type DemoCourse = Omit<Prisma.CourseUncheckedCreateInput, "id" | "createdAt" | "updatedAt">;

export const DEMO_COURSES: DemoCourse[] = [
  {
    title: "AWS Certified Solutions Architect — Associate (Demo)",
    slug: "demo-aws-certified-solutions-architect",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL, // TEST url only — each real course gets its own unique Impact URL
    image: IMG("AWS Solutions Architect"),
    imageAlt: "Demo course cover — AWS Certified Solutions Architect",
    category: "aws",
    subcategory: "certification",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Prepare for the AWS Solutions Architect Associate exam with hands-on labs and practice tests.",
    description:
      "This is clearly-marked DEMO content used to preview the NBN Market course experience. It does not represent a real Udemy course. Replace it with a real Udemy/Impact course from the admin panel.",
    price: 19.99,
    currency: "USD",
    originalPrice: 89.99,
    discountPercentage: 78,
    rating: 4.7,
    reviewCount: 12500,
    duration: "24 hours",
    lectureCount: 320,
    level: "All Levels",
    language: "English",
    certificateAvailable: true,
    bestseller: true,
    featured: true,
    lastUpdated: "2024-11",
    tags: ["aws", "cloud", "certification", "solutions architect"],
    whatYouLearn: [
      "Design resilient, scalable architectures on AWS",
      "Core services: EC2, S3, VPC, IAM, RDS and more",
      "Sit the Solutions Architect Associate exam with confidence",
    ],
    requirements: ["Basic IT and networking familiarity", "An AWS free-tier account (optional)"],
    demo: true,
    published: true,
    order: 1,
  },
  {
    title: "Python for Data Science & Machine Learning (Demo)",
    slug: "demo-python-for-data-science",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("Python for Data Science"),
    imageAlt: "Demo course cover — Python for Data Science",
    category: "python",
    subcategory: "data-science",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Learn Python, NumPy, pandas and scikit-learn for real-world data science.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 14.99,
    currency: "USD",
    originalPrice: 99.99,
    discountPercentage: 85,
    rating: 4.6,
    reviewCount: 45210,
    duration: "42 hours",
    lectureCount: 410,
    level: "Beginner",
    language: "English",
    certificateAvailable: true,
    bestseller: true,
    featured: true,
    lastUpdated: "2024-10",
    tags: ["python", "data science", "machine learning", "pandas"],
    whatYouLearn: [
      "Write clean Python for data analysis",
      "Use NumPy, pandas and Matplotlib",
      "Build and evaluate ML models with scikit-learn",
    ],
    requirements: ["No prior experience required", "A computer with internet access"],
    demo: true,
    published: true,
    order: 2,
  },
  {
    title: "The Complete React & Next.js Developer Course (Demo)",
    slug: "demo-react-nextjs-development",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("React and Next.js"),
    imageAlt: "Demo course cover — React and Next.js",
    category: "react",
    subcategory: "web-development",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Build full-stack apps with React, Next.js, the App Router and TypeScript.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 17.99,
    currency: "USD",
    originalPrice: 119.99,
    discountPercentage: 85,
    rating: 4.8,
    reviewCount: 21870,
    duration: "31 hours",
    lectureCount: 285,
    level: "Intermediate",
    language: "English",
    certificateAvailable: true,
    bestseller: false,
    featured: true,
    lastUpdated: "2025-01",
    tags: ["react", "nextjs", "typescript", "web development"],
    whatYouLearn: [
      "Build production apps with the Next.js App Router",
      "Master React hooks, server components and data fetching",
      "Deploy full-stack apps with confidence",
    ],
    requirements: ["Basic JavaScript knowledge", "Familiarity with HTML & CSS"],
    demo: true,
    published: true,
    order: 3,
  },
  {
    title: "DevOps Bootcamp: Docker, Kubernetes & CI/CD (Demo)",
    slug: "demo-devops-bootcamp-docker-kubernetes",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("DevOps Bootcamp"),
    imageAlt: "Demo course cover — DevOps Bootcamp",
    category: "devops",
    subcategory: "containers",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Ship faster with Docker, Kubernetes, Terraform and CI/CD pipelines.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 21.99,
    currency: "USD",
    originalPrice: 109.99,
    discountPercentage: 80,
    rating: 4.5,
    reviewCount: 9840,
    duration: "28 hours",
    lectureCount: 240,
    level: "Intermediate",
    language: "English",
    certificateAvailable: true,
    bestseller: false,
    featured: false,
    lastUpdated: "2024-12",
    tags: ["devops", "docker", "kubernetes", "ci/cd", "terraform"],
    whatYouLearn: [
      "Containerize applications with Docker",
      "Orchestrate workloads on Kubernetes",
      "Automate delivery with CI/CD pipelines",
    ],
    requirements: ["Command-line basics", "Some software development experience"],
    demo: true,
    published: true,
    order: 4,
  },
  {
    title: "Complete Cybersecurity & Ethical Hacking (Demo)",
    slug: "demo-cybersecurity-ethical-hacking",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("Cybersecurity"),
    imageAlt: "Demo course cover — Cybersecurity",
    category: "cybersecurity",
    subcategory: "ethical-hacking",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Learn network security, penetration testing and defensive best practices.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 16.99,
    currency: "USD",
    originalPrice: 94.99,
    discountPercentage: 82,
    rating: 4.6,
    reviewCount: 15320,
    duration: "36 hours",
    lectureCount: 350,
    level: "All Levels",
    language: "English",
    certificateAvailable: true,
    bestseller: true,
    featured: false,
    lastUpdated: "2024-09",
    tags: ["cybersecurity", "ethical hacking", "penetration testing", "security"],
    whatYouLearn: [
      "Understand common attack vectors and defences",
      "Run safe, ethical penetration tests",
      "Harden networks, systems and applications",
    ],
    requirements: ["Basic networking knowledge", "A willingness to learn hands-on"],
    demo: true,
    published: true,
    order: 5,
  },
  {
    title: "UI/UX Design Masterclass with Figma (Demo)",
    slug: "demo-ui-ux-design-figma",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("UI UX Design"),
    imageAlt: "Demo course cover — UI/UX Design",
    category: "ui-ux-design",
    subcategory: "figma",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Design beautiful, usable products with Figma from wireframe to prototype.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 13.99,
    currency: "USD",
    originalPrice: 84.99,
    discountPercentage: 84,
    rating: 4.7,
    reviewCount: 8210,
    duration: "18 hours",
    lectureCount: 160,
    level: "Beginner",
    language: "English",
    certificateAvailable: true,
    bestseller: false,
    featured: false,
    lastUpdated: "2024-11",
    tags: ["ui", "ux", "design", "figma"],
    whatYouLearn: [
      "Design wireframes and high-fidelity mockups in Figma",
      "Build interactive prototypes",
      "Apply UX research and usability principles",
    ],
    requirements: ["No design experience required", "A free Figma account"],
    demo: true,
    published: true,
    order: 6,
  },
  {
    title: "Digital Marketing & SEO Complete Course (Demo)",
    slug: "demo-digital-marketing-seo",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("Digital Marketing"),
    imageAlt: "Demo course cover — Digital Marketing",
    category: "digital-marketing",
    subcategory: "seo",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Grow traffic and sales with SEO, content, social and paid ads.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 12.99,
    currency: "USD",
    originalPrice: 74.99,
    discountPercentage: 83,
    rating: 4.4,
    reviewCount: 6720,
    duration: "22 hours",
    lectureCount: 190,
    level: "Beginner",
    language: "English",
    certificateAvailable: true,
    bestseller: false,
    featured: false,
    lastUpdated: "2024-08",
    tags: ["digital marketing", "seo", "content", "ads"],
    whatYouLearn: [
      "Rank higher with on-page and technical SEO",
      "Plan content that converts",
      "Run effective paid ad campaigns",
    ],
    requirements: ["No marketing experience required"],
    demo: true,
    published: true,
    order: 7,
  },
  {
    title: "Microsoft Azure Fundamentals AZ-900 (Demo)",
    slug: "demo-microsoft-azure-fundamentals-az900",
    provider: "Udemy",
    affiliateNetwork: "Impact",
    affiliateUrl: TEST_AFFILIATE_URL,
    image: IMG("Azure Fundamentals"),
    imageAlt: "Demo course cover — Microsoft Azure Fundamentals",
    category: "microsoft-azure",
    subcategory: "certification",
    instructor: "Demo Instructor",
    shortDescription:
      "Placeholder demo course. Pass the AZ-900 exam and learn core Azure cloud concepts.",
    description:
      "Clearly-marked DEMO content for previewing the course UI. Not a real course listing. Replace with a real Udemy/Impact course.",
    price: 15.99,
    currency: "USD",
    originalPrice: 89.99,
    discountPercentage: 82,
    rating: 4.6,
    reviewCount: 11040,
    duration: "12 hours",
    lectureCount: 120,
    level: "Beginner",
    language: "English",
    certificateAvailable: true,
    bestseller: false,
    featured: true,
    lastUpdated: "2024-12",
    tags: ["azure", "cloud", "az-900", "certification"],
    whatYouLearn: [
      "Understand core Azure services and pricing",
      "Cloud concepts, security and governance",
      "Prepare for the AZ-900 certification exam",
    ],
    requirements: ["No prior cloud experience required"],
    demo: true,
    published: true,
    order: 8,
  },
];
